name: My Starter Workflow

on:
  workflow_dispatch:

jobs:

  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/reusable-workflow.yml
        with:
          node: 14
